//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnesPmSuvorov.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreviewPages
    {
        public int PreviewPageID { get; set; }
        public string ShortText { get; set; }
        public int RepairMessageID { get; set; }
    
        public virtual RepairMessages RepairMessages { get; set; }
    }
}
